name: Upload Python Package

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools twine
    - name: Display Python version
      run: python --version
    - name: Build package
      run: python setup.py sdist
    - name: Build package
      run: twine upload dist/*
